apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  destination:
    namespace: redis
    server: "https://kubernetes.default.svc"
  project: default
  sources:
    - chart: redis
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 17.10.2
    - chart: prometheus-redis-exporter
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 5.3.2
  syncPolicy:
    automated:
      prune: true # resources deleted in Git will be deleted in the cluster
      selfHeal: true # overwrite manual changes 
    syncOptions:
    - CreateNamespace=true