apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webhook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/solkoff/argocd-kodekloud.git
    targetRevision: HEAD
    path: ./nginx-with-webhook/
  destination:
    server: https://34.74.91.155 # has be to IP
    namespace: nginx
  
  syncPolicy:
    automated:
      prune: true # resources deleted in Git will be deleted in the cluster
      selfHeal: true # overwrite manual changes
    syncOptions:
    - CreateNamespace=true
