apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-public-chart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server/ # public helm
    targetRevision: 3.8.4 # instead of BRANCH
    chart: metrics-server # which chart to install # no PATH
    helm:
      version: v3 # the latest
      releaseName: sergei-metrics
      passCredentials: false # open chart
      values: |
        replicas: 3 # default is 1
  
  destination:
    server: https://kubernetes.default.svc  
    namespace: metrics-app
  syncPolicy:
    automated:
      prune: true # resources deleted in Git will be deleted in the cluster
      selfHeal: true # overwrite manual changes
    syncOptions:
    - CreateNamespace=true
