apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-private-chart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/solkoff/argocd-kodekloud.git
    targetRevision: HEAD
    path: ./helm-private-chart/
    helm:
      version: v3
      releaseName: sergei
      
  destination:
    server: https://kubernetes.default.svc  
    namespace: helm-private
  
  syncPolicy:
    automated:
      prune: true # resources deleted in Git will be deleted in the cluster
      selfHeal: true # overwrite manual changes
    syncOptions:
    - CreateNamespace=true
