apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy
  labels:
{{- include "labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: {{ .Values.deploy.NumOfReplicas }}
  template: 
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: {{ default "richardchesterwood" .Values.deploy.DockerRepo | lower }}/k8s-fleetman-helm-demo:v1.0.0 {{- if eq .Values.environment "dev"}}-dev {{ end }}
        ports:
        - containerPort: 80
        
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-serv
spec:
  selector: 
    app: webapp
  ports:
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort